name: Deploy Frontend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t sushanthreddysingireddy/app-tracker-fronend .
      
      - name: Push Docker image
        run: docker push sushanthreddysingireddy/app-tracker-fronend:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull sushanthreddysingireddy/app-tracker-fronend:latest
        
      - name: Create Docker network
        run: docker network create app-tracker-network || true
        
      - name: Stop and remove existing container
        run: |
          docker stop app-tracker-fronend || true
          docker rm app-tracker-fronend || true
      
      - name: Run new container
        run: docker run -d --name app-tracker-fronend -p 3000:3000 --network app-tracker-network sushanthreddysingireddy/app-tracker-fronend:latest
